import { Pokemon, PokemonType, Move } from './types';

export const MOVES: Record<string, Move> = {
  Thunderbolt: { name: '十万伏特', type: PokemonType.Electric, power: 90, accuracy: 100, maxPp: 15 },
  QuickAttack: { name: '电光一闪', type: PokemonType.Normal, power: 40, accuracy: 100, maxPp: 30 },
  IronTail: { name: '铁尾', type: PokemonType.Steel, power: 100, accuracy: 75, maxPp: 15 },
  ElectroBall: { name: '电球', type: PokemonType.Electric, power: 80, accuracy: 100, maxPp: 10 },
  Flamethrower: { name: '喷射火焰', type: PokemonType.Fire, power: 90, accuracy: 100, maxPp: 15 },
  DragonClaw: { name: '龙爪', type: PokemonType.Dragon, power: 80, accuracy: 100, maxPp: 15 },
  AirSlash: { name: '空气斩', type: PokemonType.Flying, power: 75, accuracy: 95, maxPp: 15 },
  FireSpin: { name: '火焰旋涡', type: PokemonType.Fire, power: 35, accuracy: 85, maxPp: 15 },
  HydroPump: { name: '水炮', type: PokemonType.Water, power: 110, accuracy: 80, maxPp: 5 },
  SkullBash: { name: '火箭头锤', type: PokemonType.Normal, power: 130, accuracy: 100, maxPp: 10 },
  Bite: { name: '咬住', type: PokemonType.Dark, power: 60, accuracy: 100, maxPp: 25 },
  WaterGun: { name: '水枪', type: PokemonType.Water, power: 40, accuracy: 100, maxPp: 25 },
  SolarBeam: { name: '日光束', type: PokemonType.Grass, power: 120, accuracy: 100, maxPp: 10 },
  SludgeBomb: { name: '污泥炸弹', type: PokemonType.Poison, power: 90, accuracy: 100, maxPp: 10 },
  RazorLeaf: { name: '飞叶快刀', type: PokemonType.Grass, power: 55, accuracy: 95, maxPp: 25 },
  Earthquake: { name: '地震', type: PokemonType.Ground, power: 100, accuracy: 100, maxPp: 10 },
  ShadowBall: { name: '暗影球', type: PokemonType.Ghost, power: 80, accuracy: 100, maxPp: 15 },
  Psychic: { name: '精神强念', type: PokemonType.Psychic, power: 90, accuracy: 100, maxPp: 10 },
  Hypnosis: { name: '催眠术', type: PokemonType.Psychic, power: 0, accuracy: 60, maxPp: 20 },
  DreamEater: { name: '食梦', type: PokemonType.Psychic, power: 100, accuracy: 100, maxPp: 15 },
};

export const POKEMON_ROSTER: Pokemon[] = [
  {
    id: 25,
    name: '皮卡丘 (Pikachu)',
    type: PokemonType.Electric,
    maxHp: 280,
    currentHp: 280,
    attack: 55,
    defense: 40,
    speed: 90,
    moves: [MOVES.Thunderbolt, MOVES.QuickAttack, MOVES.IronTail, MOVES.ElectroBall],
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
  },
  {
    id: 6,
    name: '喷火龙 (Charizard)',
    type: PokemonType.Fire,
    maxHp: 360,
    currentHp: 360,
    attack: 84,
    defense: 78,
    speed: 100,
    moves: [MOVES.Flamethrower, MOVES.DragonClaw, MOVES.AirSlash, MOVES.FireSpin],
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',
  },
  {
    id: 9,
    name: '水箭龟 (Blastoise)',
    type: PokemonType.Water,
    maxHp: 362,
    currentHp: 362,
    attack: 83,
    defense: 100,
    speed: 78,
    moves: [MOVES.HydroPump, MOVES.SkullBash, MOVES.Bite, MOVES.WaterGun],
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png',
  },
  {
    id: 3,
    name: '妙蛙花 (Venusaur)',
    type: PokemonType.Grass,
    maxHp: 364,
    currentHp: 364,
    attack: 82,
    defense: 83,
    speed: 80,
    moves: [MOVES.SolarBeam, MOVES.SludgeBomb, MOVES.RazorLeaf, MOVES.Earthquake],
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png',
  },
  {
    id: 94,
    name: '耿鬼 (Gengar)',
    type: PokemonType.Ghost,
    maxHp: 324,
    currentHp: 324,
    attack: 65,
    defense: 60,
    speed: 110,
    moves: [MOVES.ShadowBall, MOVES.Psychic, MOVES.Hypnosis, MOVES.DreamEater],
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/94.png',
  }
];